version: '3.9'

services:
  python:
    image: assignment1
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code  
      - ./.vscode-server:/root/.vscode-server
      - ./data:/root/data
      - ./model:/root/model
    environment:
      - HOST=0.0.0.0
      - PORT=80